// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://diopahhcwhdasextobav.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpb3BhaGhjd2hkYXNleHRvYmF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1NDQ2OTQsImV4cCI6MjA3MjEyMDY5NH0.zHmqOBR19B4uFlxtaGrtTAwtcFS7j7hydACGuTv0txg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: false,
  },
  global: {
    headers: {
      'x-client-info': 'city-scope-crm@1.0.0',
    },
  },
});